#!/bin/bash
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
export OMP_NUM_THREADS=2
mpirun -n 1 ./mpi
